import hashlib
from dataclasses import dataclass
from typing import List

from .runner import ExecutionResult
from .discovery import TestNode

@dataclass
class RuleResult:
    name: str
    passed: bool
    details: str

@dataclass
class VerificationResult:
    passed: bool
    rules: List[RuleResult]

COREDUMP_MAGIC = b"UXNC"
COREDUMP_VERSION = 1
COREDUMP_STACK_SIZE = 256
COREDUMP_RAM_SIZE = 65536

def parse_coredump(data: bytes) -> dict:
    header_size = 4 + 1 + 1 + 1  # magic + version + wst_ptr + rst_ptr
    expected_size = header_size + 2 * COREDUMP_STACK_SIZE + COREDUMP_RAM_SIZE
    if len(data) != expected_size:
        raise ValueError(f"Coredump has wrong size: expected {expected_size} bytes, got {len(data)}")
    if data[0:4] != COREDUMP_MAGIC:
        raise ValueError(f"Bad coredump magic: {data[0:4]!r}")
    version = data[4]
    if version != COREDUMP_VERSION:
        raise ValueError(f"Unsupported coredump version: {version}")

    offset = 7
    wst = data[offset:offset + COREDUMP_STACK_SIZE]
    offset += COREDUMP_STACK_SIZE
    rst = data[offset:offset + COREDUMP_STACK_SIZE]
    offset += COREDUMP_STACK_SIZE
    ram = data[offset:offset + COREDUMP_RAM_SIZE]

    return {
        "wst_ptr": data[5],
        "rst_ptr": data[6],
        "wst": wst,
        "rst": rst,
        "ram": ram,
    }

class Verifier:
    def verify(self, test: TestNode, exec_res: ExecutionResult) -> VerificationResult:
        rules = []
        verify_spec = test.config.get("verify", {})

        if isinstance(verify_spec, dict):
            verify_spec = [verify_spec]

        all_passed = True

        for spec in verify_spec:
            vtype = spec.get("type")

            if vtype == "binary_match":
                res = self._check_binary_match(test, exec_res, spec)
            elif vtype == "error_match":
                res = self._check_error_match(test, exec_res, spec)
            elif vtype == "stdout_match":
                res = self._check_stdout_match(test, exec_res, spec)
            elif vtype == "hash_match":
                res = self._check_hash_match(test, exec_res, spec)
            elif vtype == "size_match":
                res = self._check_size_match(test, exec_res, spec)
            elif vtype == "coredump":
                res = self._check_coredump(test, exec_res, spec)
            else:
                res = RuleResult(vtype or "unknown", False, f"Unknown verification type: {vtype}")

            res_list = res if isinstance(res, list) else [res]
            rules.extend(res_list)
            if any(not r.passed for r in res_list):
                all_passed = False

        has_error_match = any(s.get("type") == "error_match" for s in verify_spec)
        if not has_error_match and exec_res.returncode != 0:
            rules.append(RuleResult("exit_code", False, f"Non-zero exit code: {exec_res.returncode}\nStderr: {exec_res.stderr}"))
            all_passed = False

        return VerificationResult(passed=all_passed, rules=rules)

    def _check_binary_match(self, test: TestNode, exec_res: ExecutionResult, spec: dict) -> RuleResult:
        expected_rom_rel = spec.get("expected_rom")
        if not expected_rom_rel:
            return RuleResult("binary_match", False, "Missing 'expected_rom' in config")

        expected_rom = test.path.parent / expected_rom_rel
        if not expected_rom.exists():
            return RuleResult("binary_match", False, f"Expected ROM not found at {expected_rom}")

        out_rom = exec_res.output_files.get("rom")
        if not out_rom or not out_rom.exists():
            return RuleResult("binary_match", False, "No output ROM generated by assembler.")

        with open(expected_rom, "rb") as f:
            expected_data = f.read()
        with open(out_rom, "rb") as f:
            actual_data = f.read()

        if expected_data == actual_data:
            return RuleResult("binary_match", True, "Binary identical.")
        else:
            return RuleResult("binary_match", False, f"Size: expected {len(expected_data)}, actual {len(actual_data)}")

    def _check_error_match(self, test: TestNode, exec_res: ExecutionResult, spec: dict) -> RuleResult:
        expected_err = spec.get("expected_stderr", "")
        combined = (exec_res.stderr or "") + "\n" + (exec_res.stdout or "")
        if expected_err in combined:
            return RuleResult("error_match", True, f"Found '{expected_err}' in output.")
        else:
            return RuleResult("error_match", False, f"Expected '{expected_err}' but got:\nStderr: {exec_res.stderr}\nStdout: {exec_res.stdout}")

    def _check_stdout_match(self, test: TestNode, exec_res: ExecutionResult, spec: dict) -> RuleResult:
        expected_out = spec.get("expected_stdout", "")
        if expected_out in exec_res.stdout:
            return RuleResult("stdout_match", True, f"Found '{expected_out}' in stdout.")
        else:
            return RuleResult("stdout_match", False, f"Expected '{expected_out}' but got: {exec_res.stdout}")

    def _check_hash_match(self, test: TestNode, exec_res: ExecutionResult, spec: dict) -> RuleResult:
        expected_hash = spec.get("expected_hash")
        out_rom = exec_res.output_files.get("rom")
        if not out_rom or not out_rom.exists():
            return RuleResult("hash_match", False, "No output ROM generated.")

        with open(out_rom, "rb") as f:
            actual_hash = hashlib.sha256(f.read()).hexdigest()

        if actual_hash == expected_hash:
            return RuleResult("hash_match", True, f"SHA-256 matched: {actual_hash[:8]}...")
        else:
            return RuleResult("hash_match", False, f"Hash mismatch. Expected {expected_hash}, got {actual_hash}")

    def _check_size_match(self, test: TestNode, exec_res: ExecutionResult, spec: dict) -> RuleResult:
        expected_size = spec.get("expected_size")
        out_rom = exec_res.output_files.get("rom")
        if not out_rom or not out_rom.exists():
            return RuleResult("size_match", False, "No output ROM generated.")

        actual_size = out_rom.stat().st_size
        if actual_size == expected_size:
            return RuleResult("size_match", True, f"Size matched: {actual_size} bytes.")
        else:
            return RuleResult("size_match", False, f"Size mismatch. Expected {expected_size}, got {actual_size}")

    def _check_coredump(self, test: TestNode, exec_res: ExecutionResult, spec: dict) -> List[RuleResult]:
        dump_path = exec_res.output_files.get("coredump")
        if not dump_path or not dump_path.exists():
            return [RuleResult("coredump", False, "No coredump produced by interpreter.")]

        with open(dump_path, "rb") as f:
            raw = f.read()

        try:
            state = parse_coredump(raw)
        except ValueError as e:
            return [RuleResult("coredump", False, str(e))]

        results = []

        if "wst_ptr" in spec:
            results.append(self._check_byte_field("wst_ptr", spec["wst_ptr"], state["wst_ptr"]))
        if "rst_ptr" in spec:
            results.append(self._check_byte_field("rst_ptr", spec["rst_ptr"], state["rst_ptr"]))
        if "wst" in spec:
            results.extend(self._check_stack_field("wst", spec["wst"], state["wst"], state["wst_ptr"]))
        if "rst" in spec:
            results.extend(self._check_stack_field("rst", spec["rst"], state["rst"], state["rst_ptr"]))
        if "wst_top" in spec:
            results.append(self._check_top_field("wst_top", spec["wst_top"], state["wst"], state["wst_ptr"]))
        if "rst_top" in spec:
            results.append(self._check_top_field("rst_top", spec["rst_top"], state["rst"], state["rst_ptr"]))
        if "ram" in spec:
            results.extend(self._check_ram_field(spec["ram"], state["ram"]))

        if not results:
            results.append(RuleResult("coredump", False, "No coredump fields specified to verify."))

        return results

    def _check_byte_field(self, name: str, expected: int, actual: int) -> RuleResult:
        if expected == actual:
            return RuleResult(name, True, f"{name} matched: {actual}")
        return RuleResult(name, False, f"{name} mismatch. Expected {expected}, got {actual}")

    def _check_top_field(self, name: str, expected: int, data: bytes, ptr: int) -> RuleResult:
        actual = data[(ptr - 1) & 0xff]
        if expected == actual:
            return RuleResult(name, True, f"{name} matched: {actual}")
        return RuleResult(name, False, f"{name} mismatch. Expected {expected}, got {actual}")

    def _check_stack_field(self, name: str, expected, data: bytes, ptr: int) -> List[RuleResult]:
        if isinstance(expected, dict):
            results = []
            for addr_spec, exp_val in expected.items():
                try:
                    if ".." in addr_spec:
                        start_str, end_str = addr_spec.split("..")
                        start = int(start_str, 0)
                        end = int(end_str, 0)
                    else:
                        start = int(addr_spec, 0)
                        end = start + len(exp_val) - 1
                except ValueError:
                    results.append(RuleResult(f"{name}[{addr_spec}]", False, f"Invalid address spec: {addr_spec}"))
                    continue
                
                actual = []
                for i in range(start, end + 1):
                    actual.append(data[i & 0xff])
                
                if list(exp_val) == actual:
                    results.append(RuleResult(f"{name}[{addr_spec}]", True, f"{name} matched at {addr_spec}: {actual}"))
                else:
                    results.append(RuleResult(f"{name}[{addr_spec}]", False, f"{name} mismatch at {addr_spec}. Expected {list(exp_val)}, got {actual}"))
            return results
        else:
            count = len(expected)
            actual = []
            for i in range(count):
                actual.append(data[(ptr - count + i) & 0xff])
            
            if list(expected) == actual:
                return [RuleResult(name, True, f"{name} matched: {actual}")]
            return [RuleResult(name, False, f"{name} mismatch. Expected {list(expected)}, got {actual}")]

    def _check_ram_field(self, ram_spec: dict, ram: bytes) -> List[RuleResult]:
        results = []
        for addr_spec, expected in ram_spec.items():
            try:
                if ".." in addr_spec:
                    start_str, end_str = addr_spec.split("..")
                    start = int(start_str, 0)
                    end = int(end_str, 0)
                else:
                    start = int(addr_spec, 0)
                    end = start + len(expected) - 1
            except ValueError:
                results.append(RuleResult(f"ram[{addr_spec}]", False, f"Invalid address spec: {addr_spec}"))
                continue

            actual = list(ram[start:end + 1])
            if list(expected) == actual:
                results.append(RuleResult(f"ram[{addr_spec}]", True, f"RAM matched at {addr_spec}: {actual}"))
            else:
                results.append(RuleResult(f"ram[{addr_spec}]", False, f"RAM mismatch at {addr_spec}. Expected {list(expected)}, got {actual}"))
        return results
